const en = {
  welcome: 'Welcome',
  addBeneficiary: 'Add Beneficiary',
  balance: 'Current Balance',
  recentTransactions: 'Recent Transactions',
  noTransactions: 'No transactions available.',
  delete: 'Delete',
  undo: 'Undo',
  to: 'To',
  amount: 'Amount',
  date: 'Date',
  pleaseEnterFirstName: 'Please enter first name',
  pleaseEnterLastName: 'Please enter last name',
  pleaseEnterIBAN: 'Please enter IBAN',
  invalidIBAN: 'Invalid IBAN',
  firstName: 'First Name',
  lastName: 'Last Name',
  generateIBAN: 'Generate IBAN',
  makeTransaction: 'Make Transaction',
  pleaseEnterAmount: 'Please Enter Amount',
  textErrorAmount: 'Amount must be greater than 0',
  insufficientBalance: 'Insufficient Balance',
  transferMoney: 'Transfer Money',
  choosenBeneficiary: 'Choosen Beneficiary',
  adđBeneficiary: 'Adđ Beneficiary',
};

export default en;
