const vi = {
  welcome: 'Chào mừng',
  addBeneficiary: 'Thêm Người Thụ Hưởng',
  balance: 'Số Dư Hiện Tại',
  recentTransactions: 'Giao Dịch Gần Đây',
  noTransactions: 'Chưa có giao dịch nào.',
  delete: 'Xóa',
  undo: 'Hoàn Tác',
  to: 'Đến',
  amount: 'Số tiền',
  date: 'Ngày',
  pleaseEnterFirstName: 'Vui lòng nhập tên',
  pleaseEnterLastName: 'Vui lòng nhập họ',
  pleaseEnterIBAN: 'Vui lòng nhập IBAN',
  invalidIBAN: 'IBAN không hợp lệ',
  firstName: 'Tên',
  lastName: 'Họ',
  generateIBAN: 'Tạo IBAN tự động',
  makeTransaction: 'Thực hiện giao dịch',
  pleaseEnterAmount: 'Vui lòng nhập số tiền',
  textErrorAmount: 'Số tiền phải lớn hơn 0',
  insufficientBalance: 'Số dư không đủ',
  transferMoney: 'Chuyển tiền',
  choosenBeneficiary: 'Chọn người thừa hưởng',
  adđBeneficiary: 'Thêm vào người thụ hưởng',
};

export default vi;
